# This shows in chat before messages sent by the plugin
chat-prefix: "&8&l[&9uSkyFix&8&l]&r "

# These are all the permissions for the plugin
permissions:
    place-sign: "uSkyFix.sign.place"
    break-sign: "uSkyFix.sign.break"
    command: "uSkyFix.command"

# These are all the messages for the plugin
messages:
    sign-placed: "&bSign placed"
    sign-broken: "&bSign removed"
    no-permission: "&cYou dont' have permission to do that!"
    error: "&cSomething went wrong!"
    version: "&bThis server is running &7{version}"
    command-usage: "&bUsage: &7/uskyfix [reload|refresh]"
    config-reloaded: "&bConfig reloaded"
    refreshed: "&bLeaderboards refreshed"

# Internal, don't change this
config-version: 2
