main: com.perceivedev.uskyfix.uSkyFix
name: uSkyFix
description: Fixes and additions for uSkyBlock
version: 1.1.2
depend: [PlaceholderAPI,uSkyBlock]
commands:
    uskyfix:
        description: The main command for uSkyFix
        aliases: [usf]
        usage: Rayzr forgot to register his commands again...
